### ISSUE TITLE
xia2.get_unit_cell_errors crashes

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#33]
Using the xia2 processing folder of #32:

```
 $ xia2.get_unit_cell_errors 
Environment configuration...
Python => /dls_sw/apps/dials/dials-v1-2-4/build/../base/bin/python2.7
CCTBX => /dls_sw/apps/dials/dials-v1-2-4/modules
CCP4 => /dls_sw/apps/ccp4/64/7.0/update7/ccp4-7.0
CLIBD => /dls_sw/apps/ccp4/64/7.0/update7/ccp4-7.0/lib/data
CCP4_SCR => /tmp/tmpHyd2jL
Working directory: /dls/tmp/wra62962/directories/Bbzl1mgT/oldxia2
Free space:        4424.76 GB
Host: cs04r-sc-com99-09
Contact: xia2.support@gmail.com
XIA2 0.4.0.342-ge8fbd7c-dials-1.2
Status: error "'NoneType' object has no attribute 'get_epochs'"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com

$ cat xia2.error 
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-2-4/build/../modules/xia2/command_line/get_unit_cell_errors.py", line 305, in run
    get_unit_cell_errors()
  File "/dls_sw/apps/dials/dials-v1-2-4/build/../modules/xia2/command_line/get_unit_cell_errors.py", line 157, in get_unit_cell_errors
    all_miller_indices, all_two_thetas_obs, reference_cell, reference_lattice, reference_wavelength = load_sweeps_with_common_indexing()
  File "/dls_sw/apps/dials/dials-v1-2-4/build/../modules/xia2/command_line/get_unit_cell_errors.py", line 46, in load_sweeps_with_common_indexing
    epochs = scaler._sweep_handler.get_epochs()
AttributeError: 'NoneType' object has no attribute 'get_epochs'
```

same with 1.2.4 and nightly

**Comment by Anthchirp** [comment]
Caused by #32. Fixed now.
